version: "3"
services:
  db:
    build: 
      context: db
      dockerfile: Dockerfile
    networks:
      - book-scraper-network
    container_name: db
  
  scraper:
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - book-scraper-network
    command: dockerize -wait tcp://db:5432 -timeout 30s python book_scraper/main.py

networks:
  book-scraper-network: