@echo off
echo Creating python virtual environment...
python -m venv .venv
echo Activating python virtual environment...
call .venv\Scripts\activate.bat
echo Installing required packages...
pip install -r book_scraper/requirements.txt
echo Running book scraper...
python book_scraper/main.py
call deactivate
echo Deactivating python virtual environment...
pause